#!/bin/bash
# A. Lochmann 2017
# This script converts the instruction pointers of an input file
# to code positions. The input file is the output generated by get-counterexamples.sh.
# This scripts forwards all columns of the input file, and adds the code position where 
# the instruction pointer points to.

if [ ${#} -lt 3 ];
then
	echo "usage: ${0} <input file> <vmlinux> <output file>"
	exit 1
fi

DELIMITER=';'
INPUT=${1}; shift
VMLINUX=${1}; shift
OUTPUT=${1}; shift

while read line
do
	INSTRPTR=`echo ${line} | cut -d ${DELIMITER} -f 2`
	POS=`addr2line -e ${VMLINUX} ${INSTRPTR}`
	echo ${line}${DELIMITER}${POS} >> ${OUTPUT}
done < ${INPUT}

