#!/bin/bash
CONFIGFILE="convert.conf"
TOOLS_PATH=`dirname ${0}`
BASE_URL="https://ess.cs.tu-dortmund.de/pferd/linux-lockdoc/lockdebug-v4.10-0.11"

function usage() {
	echo "usage: $0 <database> <data_type> <variant: nostack vs. stack>" >&2
	exit 1
}

if [ ${#} -lt 3 ];
then
	usage ${0}
fi
DB=${1};shift
DATA_TYPE=${1};shift
VARIANT=${1};shift

if [ ! -f ${CONFIGFILE} ];
then
	echo "${CONFIGFILE} does not exist!" >&2
	echo "The config file must define the following variables:
KERNEL		The vmlinux image used by the vm
DATA		The csv file generated by FAIL* which contains the events
DELIMITER	Delimiter used by FAIL*, e.g., ';' oder '#'
It may contain one of the following vars to override the default values:
CONVERT_BINARY	An alternative convert binary, e.g., an old version
DATA_TYPES	The list of data types which should be processed
FN_BLACK_LIST	Blacklisted functions
MEMBER_BLACK_LIST Blacklisted members" >&2
	exit 1
fi
. ${CONFIGFILE}

if [ -z ${KERNEL} ];
then
	echo "Variable KERNEL is not set!" >&2
	exit 1
fi

if [ ${VARIANT} != "nostack" ] && [ ${VARIANT} != "stack" ];
then
	usage ${0}
	exit 1
fi

if [ ${DATA_TYPE} == "any" ];
then
	CEX_CSV="cex-${VARIANT}.csv"
	CEX_HTML="cex-${VARIANT}.html"
else
	CEX_CSV="cex-${VARIANT}-${DATA_TYPE}.csv"
	CEX_HTML="cex-${VARIANT}-${DATA_TYPE}.html"
fi


time ${TOOLS_PATH}/get-counterexamples.sh all_txns_members_locks_hypo_bugs_${VARIANT}.txt ${DATA_TYPE} ${DB} 1 > ${CEX_CSV}
if [ ${?} -ne 0 ];
then
	echo "Cannot run get-counterexamples.sh for ${VARIANT}!">&2 
	exit 1
fi

${TOOLS_PATH}/pretty-print-cex.py -u ${BASE_URL} ${CEX_CSV} ${KERNEL} all_txns_members_locks_hypo_winner_${VARIANT}.csv > ${CEX_HTML}
if [ ${?} -ne 0 ];
then
	echo "Cannot run pretty-print-cex.py for ${VARIANT}!">&2 
	exit 1
fi
